
platform :ios, '8.0'

def js()
    use_frameworks!
    pod 'HighlightJS', :path => '../'
end

target 'Sample' do
  use_frameworks!
  pod 'ActionSheetPicker-3.0'
  js()
end

target 'macOS' do
    js()
end

target 'tvOS' do
    js()
end
